"""Adds the annotations.category column

Revision ID: b6a2e4a41ee4
Revises: b2bea80e7052
Create Date: 2017-08-22 15:51:06.756876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a2e4a41ee4'
down_revision = 'b2bea80e7052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('category', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'category')
    # ### end Alembic commands ###
